import React,{Component} from 'react';
import ReactDOM from 'react-dom';
import {CJSelect,CJCascade} from './components/index';
// import { CJCascade,CJSelect} from 'chejianer-lib-ts';

let options=[
    {
        "A":[
            {
                "brand":"阿尔法-罗密欧",
                "brandPicName":"ALFA_ROMEO",
                "brandPicUrl":"http://brand-logo.oss-cn-shanghai.aliyuncs.com/ALFA_ROMEO.png"
            },
            {
                "brand":"奥迪",
                "brandPicName":"AUDI",
                "brandPicUrl":"http://brand-logo.oss-cn-shanghai.aliyuncs.com/AUDI.png"
            },
            {
                "brand":"阿斯顿马丁",
                "brandPicName":"ASTON-MARTIN",
                "brandPicUrl":"http://brand-logo.oss-cn-shanghai.aliyuncs.com/ASTON-MARTIN.png"
            }
        ],
    },
    {
        "B":[
            {
                "brand":"保时捷",
                "brandPicName":"PORSCHE",
                "brandPicUrl":"http://brand-logo.oss-cn-shanghai.aliyuncs.com/PORSCHE.png"
            },
            {
                "brand":"绅宝",
                "brandPicName":"BEIQI",
                "brandPicUrl":"http://brand-logo.oss-cn-shanghai.aliyuncs.com/BEIQI.png"
            },
            {
                "brand":"别克",
                "brandPicName":"BUICK",
                "brandPicUrl":"http://brand-logo.oss-cn-shanghai.aliyuncs.com/BUICK.png"
            },
            {
                "brand":"本田",
                "brandPicName":"HONDA",
                "brandPicUrl":"http://brand-logo.oss-cn-shanghai.aliyuncs.com/HONDA.png"
            },
            {
                "brand":"奔驰",
                "brandPicName":"BENZ",
                "brandPicUrl":"http://brand-logo.oss-cn-shanghai.aliyuncs.com/BENZ.png"
            },
            {
                "brand":"宾利",
                "brandPicName":"BENTLEY",
                "brandPicUrl":"http://brand-logo.oss-cn-shanghai.aliyuncs.com/BENTLEY.png"
            },
            {
                "brand":"北汽",
                "brandPicName":"BAW",
                "brandPicUrl":"http://brand-logo.oss-cn-shanghai.aliyuncs.com/BAW.png"
            },
            {
                "brand":"比速",
                "brandPicName":"BISU",
                "brandPicUrl":"http://brand-logo.oss-cn-shanghai.aliyuncs.com/BISU.png"
            },
            {
                "brand":"宝沃",
                "brandPicName":"BAOWO",
                "brandPicUrl":"http://brand-logo.oss-cn-shanghai.aliyuncs.com/BAOWO.png"
            },
            {
                "brand":"比亚迪",
                "brandPicName":"BYD",
                "brandPicUrl":"http://brand-logo.oss-cn-shanghai.aliyuncs.com/BYD.png"
            },
            {
                "brand":"宝骏",
                "brandPicName":"BAOJUN",
                "brandPicUrl":"http://brand-logo.oss-cn-shanghai.aliyuncs.com/BAOJUN.png"
            },
            {
                "brand":"幻速",
                "brandPicName":"BEIQIHUANSU",
                "brandPicUrl":"http://brand-logo.oss-cn-shanghai.aliyuncs.com/BEIQIHUANSU.png"
            },
            {
                "brand":"威旺",
                "brandPicName":"WEIWANG",
                "brandPicUrl":"http://brand-logo.oss-cn-shanghai.aliyuncs.com/WEIWANG.png"
            },
            {
                "brand":"标致",
                "brandPicName":"PEUGOET",
                "brandPicUrl":"http://brand-logo.oss-cn-shanghai.aliyuncs.com/PEUGOET.png"
            },
            {
                "brand":"宝马",
                "brandPicName":"BMW",
                "brandPicUrl":"http://brand-logo.oss-cn-shanghai.aliyuncs.com/BMW.png"
            },
            {
                "brand":"巴博斯",
                "brandPicName":"BARBUS",
                "brandPicUrl":"http://brand-logo.oss-cn-shanghai.aliyuncs.com/BARBUS.png"
            },
            {
                "brand":"北京",
                "brandPicName":"BEIQI",
                "brandPicUrl":"http://brand-logo.oss-cn-shanghai.aliyuncs.com/BEIQI.png"
            }
        ]
    },
    {
        "C":[
            {
                "brand":"长城",
                "brandPicName":"GREATWALL",
                "brandPicUrl":"http://brand-logo.oss-cn-shanghai.aliyuncs.com/GREATWALL.png"
            },
            {
                "brand":"昌河",
                "brandPicName":"CHANGHE",
                "brandPicUrl":"http://brand-logo.oss-cn-shanghai.aliyuncs.com/CHANGHE.png"
            },
            {
                "brand":"长安",
                "brandPicName":"CHANGAN",
                "brandPicUrl":"http://brand-logo.oss-cn-shanghai.aliyuncs.com/CHANGAN.png"
            },
            {
                "brand":"长安商用",
                "brandPicName":"CHANGANSHANGYONG",
                "brandPicUrl":"http://brand-logo.oss-cn-shanghai.aliyuncs.com/CHANGANSHANGYONG.png"
            }
        ]
    },
    {
        "D":[
            {
                "brand":"东南",
                "brandPicName":"SOUEAST",
                "brandPicUrl":"http://brand-logo.oss-cn-shanghai.aliyuncs.com/SOUEAST.png"
            },
            {
                "brand":"DS",
                "brandPicName":"DS",
                "brandPicUrl":"http://brand-logo.oss-cn-shanghai.aliyuncs.com/DS.png"
            },
            {
                "brand":"启辰",
                "brandPicName":"QICHEN",
                "brandPicUrl":"http://brand-logo.oss-cn-shanghai.aliyuncs.com/QICHEN.png"
            },
            {
                "brand":"纳智捷",
                "brandPicName":"LUXGEN",
                "brandPicUrl":"http://brand-logo.oss-cn-shanghai.aliyuncs.com/LUXGEN.png"
            },
            {
                "brand":"东风风度",
                "brandPicName":"DONGFENG",
                "brandPicUrl":"http://brand-logo.oss-cn-shanghai.aliyuncs.com/DONGFENG.png"
            },
            {
                "brand":"大迪",
                "brandPicName":"DADI",
                "brandPicUrl":"http://brand-logo.oss-cn-shanghai.aliyuncs.com/DADI.png"
            },
            {
                "brand":"思铭",
                "brandPicName":"CIIMO",
                "brandPicUrl":"http://brand-logo.oss-cn-shanghai.aliyuncs.com/CIIMO.png"
            },
            {
                "brand":"东风小康",
                "brandPicName":"DONGFENG",
                "brandPicUrl":"http://brand-logo.oss-cn-shanghai.aliyuncs.com/DONGFENG.png"
            },
            {
                "brand":"大众",
                "brandPicName":"VW",
                "brandPicUrl":"http://brand-logo.oss-cn-shanghai.aliyuncs.com/VW.png"
            },
            {
                "brand":"风行",
                "brandPicName":"DONGFENG",
                "brandPicUrl":"http://brand-logo.oss-cn-shanghai.aliyuncs.com/DONGFENG.png"
            },
            {
                "brand":"道奇",
                "brandPicName":"DODGE",
                "brandPicUrl":"http://brand-logo.oss-cn-shanghai.aliyuncs.com/DODGE.png"
            },
            {
                "brand":"风神",
                "brandPicName":"DONGFENG",
                "brandPicUrl":"http://brand-logo.oss-cn-shanghai.aliyuncs.com/DONGFENG.png"
            }
        ],
    },
    {
        "F":[
            {
                "brand":"丰田",
                "brandPicName":"TOYOTA",
                "brandPicUrl":"http://brand-logo.oss-cn-shanghai.aliyuncs.com/TOYOTA.png"
            },
            {
                "brand":"启腾",
                "brandPicName":"FQT",
                "brandPicUrl":"http://brand-logo.oss-cn-shanghai.aliyuncs.com/FQT.png"
            },
            {
                "brand":"法拉利",
                "brandPicName":"FERRARI",
                "brandPicUrl":"http://brand-logo.oss-cn-shanghai.aliyuncs.com/FERRARI.png"
            },
            {
                "brand":"福田",
                "brandPicName":"FOTON",
                "brandPicUrl":"http://brand-logo.oss-cn-shanghai.aliyuncs.com/FOTON.png"
            },
            {
                "brand":"菲亚特",
                "brandPicName":"FIAT",
                "brandPicUrl":"http://brand-logo.oss-cn-shanghai.aliyuncs.com/FIAT.png"
            },
            {
                "brand":"富奇",
                "brandPicName":"FUQI",
                "brandPicUrl":"http://brand-logo.oss-cn-shanghai.aliyuncs.com/FUQI.png"
            },
            {
                "brand":"福迪",
                "brandPicName":"FUDI",
                "brandPicUrl":"http://brand-logo.oss-cn-shanghai.aliyuncs.com/FUDI.png"
            },
            {
                "brand":"福特",
                "brandPicName":"FORD",
                "brandPicUrl":"http://brand-logo.oss-cn-shanghai.aliyuncs.com/FORD.png"
            }
        ]
    },
    {
        "G":[
            {
                "brand":"吉奥",
                "brandPicName":"GONOW",
                "brandPicUrl":"http://brand-logo.oss-cn-shanghai.aliyuncs.com/GONOW.png"
            },
            {
                "brand":"理念",
                "brandPicName":"EVERUS",
                "brandPicUrl":"http://brand-logo.oss-cn-shanghai.aliyuncs.com/EVERUS.png"
            },
            {
                "brand":"传祺",
                "brandPicName":"TRUMPCHI",
                "brandPicUrl":"http://brand-logo.oss-cn-shanghai.aliyuncs.com/TRUMPCHI.png"
            },
            {
                "brand":"光冈",
                "brandPicName":"MITSUOKA",
                "brandPicUrl":"http://brand-logo.oss-cn-shanghai.aliyuncs.com/MITSUOKA.png"
            },
            {
                "brand":"观致",
                "brandPicName":"QOROS",
                "brandPicUrl":"http://brand-logo.oss-cn-shanghai.aliyuncs.com/QOROS.png"
            }
        ]
    },
    {
        "H":[
            {
                "brand":"华泰",
                "brandPicName":"HAWTAI",
                "brandPicUrl":"http://brand-logo.oss-cn-shanghai.aliyuncs.com/HAWTAI.png"
            },
            {
                "brand":"哈弗",
                "brandPicName":"HAVAL",
                "brandPicUrl":"http://brand-logo.oss-cn-shanghai.aliyuncs.com/HAVAL.png"
            },
            {
                "brand":"黄海",
                "brandPicName":"HUANGHAI",
                "brandPicUrl":"http://brand-logo.oss-cn-shanghai.aliyuncs.com/HUANGHAI.png"
            },
            {
                "brand":"华阳",
                "brandPicName":"HUAYANG",
                "brandPicUrl":"http://brand-logo.oss-cn-shanghai.aliyuncs.com/HUAYANG.png"
            },
            {
                "brand":"汉腾",
                "brandPicName":"HANTENG",
                "brandPicUrl":"http://brand-logo.oss-cn-shanghai.aliyuncs.com/HANTENG.png"
            },
            {
                "brand":"华颂",
                "brandPicName":"HUASONG",
                "brandPicUrl":"http://brand-logo.oss-cn-shanghai.aliyuncs.com/HUASONG.png"
            },
            {
                "brand":"华骐",
                "brandPicName":"HUAQI",
                "brandPicUrl":"http://brand-logo.oss-cn-shanghai.aliyuncs.com/HUAQI.png"
            },
            {
                "brand":"哈飞",
                "brandPicName":"HAFEI",
                "brandPicUrl":"http://brand-logo.oss-cn-shanghai.aliyuncs.com/HAFEI.png"
            },
            {
                "brand":"海马",
                "brandPicName":"HAIMA",
                "brandPicUrl":"http://brand-logo.oss-cn-shanghai.aliyuncs.com/HAIMA.png"
            }
        ]
    },
    {
        "J":[
            {
                "brand":"全球鹰",
                "brandPicName":"EAGLE",
                "brandPicUrl":"http://brand-logo.oss-cn-shanghai.aliyuncs.com/EAGLE.png"
            },
            {
                "brand":"江铃",
                "brandPicName":"JMC",
                "brandPicUrl":"http://brand-logo.oss-cn-shanghai.aliyuncs.com/JMC.png"
            },
            {
                "brand":"金杯",
                "brandPicName":"JINBEI",
                "brandPicUrl":"http://brand-logo.oss-cn-shanghai.aliyuncs.com/JINBEI.png"
            },
            {
                "brand":"英伦",
                "brandPicName":"ENGLON",
                "brandPicUrl":"http://brand-logo.oss-cn-shanghai.aliyuncs.com/ENGLON.png"
            },
            {
                "brand":"Jeep",
                "brandPicName":"JEEP",
                "brandPicUrl":"http://brand-logo.oss-cn-shanghai.aliyuncs.com/JEEP.png"
            },
            {
                "brand":"吉利",
                "brandPicName":"GEELY",
                "brandPicUrl":"http://brand-logo.oss-cn-shanghai.aliyuncs.com/GEELY.png"
            },
            {
                "brand":"江南",
                "brandPicName":"JIANGNAN",
                "brandPicUrl":"http://brand-logo.oss-cn-shanghai.aliyuncs.com/JIANGNAN.png"
            },
            {
                "brand":"帝豪",
                "brandPicName":"DIHAO",
                "brandPicUrl":"http://brand-logo.oss-cn-shanghai.aliyuncs.com/DIHAO.png"
            },
            {
                "brand":"捷豹",
                "brandPicName":"JAGUAR",
                "brandPicUrl":"http://brand-logo.oss-cn-shanghai.aliyuncs.com/JAGUAR.png"
            },
            {
                "brand":"江淮",
                "brandPicName":"JAC",
                "brandPicUrl":"http://brand-logo.oss-cn-shanghai.aliyuncs.com/JAC.png"
            }
        ]
    },
    {
        "K":[
            {
                "brand":"开瑞",
                "brandPicName":"KARRY",
                "brandPicUrl":"http://brand-logo.oss-cn-shanghai.aliyuncs.com/KARRY.png"
            },
            {
                "brand":"克莱斯勒",
                "brandPicName":"CHRYSLER",
                "brandPicUrl":"http://brand-logo.oss-cn-shanghai.aliyuncs.com/CHRYSLER.png"
            },
            {
                "brand":"凯翼",
                "brandPicName":"COWIN",
                "brandPicUrl":"http://brand-logo.oss-cn-shanghai.aliyuncs.com/COWIN.png"
            },
            {
                "brand":"卡威",
                "brandPicName":"KAWEI",
                "brandPicUrl":"http://brand-logo.oss-cn-shanghai.aliyuncs.com/KAWEI.png"
            },
            {
                "brand":"凯迪拉克",
                "brandPicName":"CADILLAC",
                "brandPicUrl":"http://brand-logo.oss-cn-shanghai.aliyuncs.com/CADILLAC.png"
            }
        ]
    },
    {
        "L":[
            {
                "brand":"莲花",
                "brandPicName":"LotusYM",
                "brandPicUrl":"http://brand-logo.oss-cn-shanghai.aliyuncs.com/LotusYM.png"
            },
            {
                "brand":"兰博基尼",
                "brandPicName":"LAMBORGHINI",
                "brandPicUrl":"http://brand-logo.oss-cn-shanghai.aliyuncs.com/LAMBORGHINI.png"
            },
            {
                "brand":"路特斯",
                "brandPicName":"LOTUS",
                "brandPicUrl":"http://brand-logo.oss-cn-shanghai.aliyuncs.com/LOTUS.png"
            },
            {
                "brand":"雷克萨斯",
                "brandPicName":"LEXUS",
                "brandPicUrl":"http://brand-logo.oss-cn-shanghai.aliyuncs.com/LEXUS.png"
            },
            {
                "brand":"林肯",
                "brandPicName":"LINCOLN",
                "brandPicUrl":"http://brand-logo.oss-cn-shanghai.aliyuncs.com/LINCOLN.png"
            },
            {
                "brand":"路虎",
                "brandPicName":"LANDROVER",
                "brandPicUrl":"http://brand-logo.oss-cn-shanghai.aliyuncs.com/LANDROVER.png"
            },
            {
                "brand":"劳斯莱斯",
                "brandPicName":"ROLLS-ROYCE",
                "brandPicUrl":"http://brand-logo.oss-cn-shanghai.aliyuncs.com/ROLLS-ROYCE.png"
            },
            {
                "brand":"力帆",
                "brandPicName":"LIFAN",
                "brandPicUrl":"http://brand-logo.oss-cn-shanghai.aliyuncs.com/LIFAN.png"
            },
            {
                "brand":"扬子",
                "brandPicName":"YANGZI",
                "brandPicUrl":"http://brand-logo.oss-cn-shanghai.aliyuncs.com/YANGZI.png"
            },
            {
                "brand":"陆风",
                "brandPicName":"LANDWIND",
                "brandPicUrl":"http://brand-logo.oss-cn-shanghai.aliyuncs.com/LANDWIND.png"
            },
            {
                "brand":"猎豹",
                "brandPicName":"LEOPAARD",
                "brandPicUrl":"http://brand-logo.oss-cn-shanghai.aliyuncs.com/LEOPAARD.png"
            },
            {
                "brand":"铃木",
                "brandPicName":"SUZUKI",
                "brandPicUrl":"http://brand-logo.oss-cn-shanghai.aliyuncs.com/SUZUKI.png"
            },
            {
                "brand":"雷诺",
                "brandPicName":"RENAULT",
                "brandPicUrl":"http://brand-logo.oss-cn-shanghai.aliyuncs.com/RENAULT.png"
            }
        ]
    },
    {
        "M":[
            {
                "brand":"MINI",
                "brandPicName":"MINI",
                "brandPicUrl":"http://brand-logo.oss-cn-shanghai.aliyuncs.com/MINI.png"
            },
            {
                "brand":"美亚",
                "brandPicName":"MEIYA",
                "brandPicUrl":"http://brand-logo.oss-cn-shanghai.aliyuncs.com/MEIYA.png"
            },
            {
                "brand":"迈凯伦",
                "brandPicName":"MCLAREN",
                "brandPicUrl":"http://brand-logo.oss-cn-shanghai.aliyuncs.com/MCLAREN.png"
            },
            {
                "brand":"玛莎拉蒂",
                "brandPicName":"MASERATI",
                "brandPicUrl":"http://brand-logo.oss-cn-shanghai.aliyuncs.com/MASERATI.png"
            },
            {
                "brand":"马自达",
                "brandPicName":"MAZDA",
                "brandPicUrl":"http://brand-logo.oss-cn-shanghai.aliyuncs.com/MAZDA.png"
            },
            {
                "brand":"MG",
                "brandPicName":"MG",
                "brandPicUrl":"http://brand-logo.oss-cn-shanghai.aliyuncs.com/MG.png"
            }
        ]
    },
    {
        "O":[
            {
                "brand":"欧宝",
                "brandPicName":"OPEL",
                "brandPicUrl":"http://brand-logo.oss-cn-shanghai.aliyuncs.com/OPEL.png"
            },
            {
                "brand":"讴歌",
                "brandPicName":"ACURA",
                "brandPicUrl":"http://brand-logo.oss-cn-shanghai.aliyuncs.com/ACURA.png"
            }
        ]
    },
    {
        "Q":[
            {
                "brand":"瑞麒",
                "brandPicName":"RIICH",
                "brandPicUrl":"http://brand-logo.oss-cn-shanghai.aliyuncs.com/RIICH.png"
            },
            {
                "brand":"起亚",
                "brandPicName":"KIA",
                "brandPicUrl":"http://brand-logo.oss-cn-shanghai.aliyuncs.com/KIA.png"
            },
            {
                "brand":"奇瑞",
                "brandPicName":"CHERY",
                "brandPicUrl":"http://brand-logo.oss-cn-shanghai.aliyuncs.com/CHERY.png"
            },
            {
                "brand":"威麟",
                "brandPicName":"RELY",
                "brandPicUrl":"http://brand-logo.oss-cn-shanghai.aliyuncs.com/RELY.png"
            }
        ]
    },
    {
        "R":[
            {
                "brand":"日产",
                "brandPicName":"NISSAN",
                "brandPicUrl":"http://brand-logo.oss-cn-shanghai.aliyuncs.com/NISSAN.png"
            },
            {
                "brand":"RUF",
                "brandPicName":"RUF",
                "brandPicUrl":"http://brand-logo.oss-cn-shanghai.aliyuncs.com/RUF.png"
            },
            {
                "brand":"荣威",
                "brandPicName":"ROEWE",
                "brandPicUrl":"http://brand-logo.oss-cn-shanghai.aliyuncs.com/ROEWE.png"
            }
        ]
    },
    {
        "S":[
            {
                "brand":"三菱",
                "brandPicName":"MITSUBISHI",
                "brandPicUrl":"http://brand-logo.oss-cn-shanghai.aliyuncs.com/MITSUBISHI.png"
            },
            {
                "brand":"双环",
                "brandPicName":"SHUANGHUAN",
                "brandPicUrl":"http://brand-logo.oss-cn-shanghai.aliyuncs.com/SHUANGHUAN.png"
            },
            {
                "brand":"双龙",
                "brandPicName":"SSANGYONG",
                "brandPicUrl":"http://brand-logo.oss-cn-shanghai.aliyuncs.com/SSANGYONG.png"
            },
            {
                "brand":"Smart",
                "brandPicName":"SMART",
                "brandPicUrl":"http://brand-logo.oss-cn-shanghai.aliyuncs.com/SMART.png"
            },
            {
                "brand":"SPRINGO",
                "brandPicName":"SPRINGO",
                "brandPicUrl":"http://brand-logo.oss-cn-shanghai.aliyuncs.com/SPRINGO.png"
            },
            {
                "brand":"斯巴鲁",
                "brandPicName":"SUBARU",
                "brandPicUrl":"http://brand-logo.oss-cn-shanghai.aliyuncs.com/SUBARU.png"
            },
            {
                "brand":"斯威",
                "brandPicName":"SIWEI",
                "brandPicUrl":"http://brand-logo.oss-cn-shanghai.aliyuncs.com/SIWEI.png"
            },
            {
                "brand":"华普",
                "brandPicName":"MAPLE",
                "brandPicUrl":"http://brand-logo.oss-cn-shanghai.aliyuncs.com/MAPLE.png"
            },
            {
                "brand":"斯柯达",
                "brandPicName":"SKODA",
                "brandPicUrl":"http://brand-logo.oss-cn-shanghai.aliyuncs.com/SKODA.png"
            }
        ]
    },
    {
        "T":[
            {
                "brand":"腾势",
                "brandPicName":"DENZA",
                "brandPicUrl":"http://brand-logo.oss-cn-shanghai.aliyuncs.com/DENZA.png"
            },
            {
                "brand":"特斯拉",
                "brandPicName":"TESLA",
                "brandPicUrl":"http://brand-logo.oss-cn-shanghai.aliyuncs.com/TESLA.png"
            },
            {
                "brand":"天马",
                "brandPicName":"TIANMA",
                "brandPicUrl":"http://brand-logo.oss-cn-shanghai.aliyuncs.com/TIANMA.png"
            }
        ]
    },
    {
        "W":[
            {
                "brand":"五十铃",
                "brandPicName":"ISUZU",
                "brandPicUrl":"http://brand-logo.oss-cn-shanghai.aliyuncs.com/ISUZU.png"
            },
            {
                "brand":"五菱",
                "brandPicName":"WULING",
                "brandPicUrl":"http://brand-logo.oss-cn-shanghai.aliyuncs.com/WULING.png"
            },
            {
                "brand":"威兹曼",
                "brandPicName":"WIESMANN",
                "brandPicUrl":"http://brand-logo.oss-cn-shanghai.aliyuncs.com/WIESMANN.png"
            },
            {
                "brand":"WEY",
                "brandPicName":"WEY",
                "brandPicUrl":"http://brand-logo.oss-cn-shanghai.aliyuncs.com/WEY.png"
            },
            {
                "brand":"沃尔沃",
                "brandPicName":"VOLVO",
                "brandPicUrl":"http://brand-logo.oss-cn-shanghai.aliyuncs.com/VOLVO.png"
            }
        ]
    },
    {
        "X":[
            {
                "brand":"西雅特",
                "brandPicName":"SEAT",
                "brandPicUrl":"http://brand-logo.oss-cn-shanghai.aliyuncs.com/SEAT.png"
            },
            {
                "brand":"雪铁龙",
                "brandPicName":"CITROEN",
                "brandPicUrl":"http://brand-logo.oss-cn-shanghai.aliyuncs.com/CITROEN.png"
            },
            {
                "brand":"新雅途",
                "brandPicName":"XINYATU",
                "brandPicUrl":"http://brand-logo.oss-cn-shanghai.aliyuncs.com/XINYATU.png"
            },
            {
                "brand":"现代",
                "brandPicName":"HYUNDAI",
                "brandPicUrl":"http://brand-logo.oss-cn-shanghai.aliyuncs.com/HYUNDAI.png"
            },
            {
                "brand":"新凯",
                "brandPicName":"XINKAI",
                "brandPicUrl":"http://brand-logo.oss-cn-shanghai.aliyuncs.com/XINKAI.png"
            },
            {
                "brand":"雪佛兰",
                "brandPicName":"CHEVROLET",
                "brandPicUrl":"http://brand-logo.oss-cn-shanghai.aliyuncs.com/CHEVROLET.png"
            }
        ]
    },
    {
        "Y":[
            {
                "brand":"一汽",
                "brandPicName":"FAW",
                "brandPicUrl":"http://brand-logo.oss-cn-shanghai.aliyuncs.com/FAW.png"
            },
            {
                "brand":"奔腾",
                "brandPicName":"FAW",
                "brandPicUrl":"http://brand-logo.oss-cn-shanghai.aliyuncs.com/FAW.png"
            },
            {
                "brand":"云度",
                "brandPicName":"YUNDU",
                "brandPicUrl":"http://brand-logo.oss-cn-shanghai.aliyuncs.com/YUNDU.png"
            },
            {
                "brand":"英致",
                "brandPicName":"WEICHAI",
                "brandPicUrl":"http://brand-logo.oss-cn-shanghai.aliyuncs.com/WEICHAI.png"
            },
            {
                "brand":"夏利",
                "brandPicName":"FAW",
                "brandPicUrl":"http://brand-logo.oss-cn-shanghai.aliyuncs.com/FAW.png"
            },
            {
                "brand":"大发",
                "brandPicName":"DAFA",
                "brandPicUrl":"http://brand-logo.oss-cn-shanghai.aliyuncs.com/DAFA.png"
            },
            {
                "brand":"红旗",
                "brandPicName":"HONGQI",
                "brandPicUrl":"http://brand-logo.oss-cn-shanghai.aliyuncs.com/HONGQI.png"
            },
            {
                "brand":"野马",
                "brandPicName":"YEMA",
                "brandPicUrl":"http://brand-logo.oss-cn-shanghai.aliyuncs.com/YEMA.png"
            },
            {
                "brand":"欧朗",
                "brandPicName":"FAW",
                "brandPicUrl":"http://brand-logo.oss-cn-shanghai.aliyuncs.com/FAW.png"
            },
            {
                "brand":"永源",
                "brandPicName":"JONWAY",
                "brandPicUrl":"http://brand-logo.oss-cn-shanghai.aliyuncs.com/JONWAY.png"
            },
            {
                "brand":"通用",
                "brandPicName":"FAW",
                "brandPicUrl":"http://brand-logo.oss-cn-shanghai.aliyuncs.com/FAW.png"
            },
            {
                "brand":"英菲尼迪",
                "brandPicName":"INFINITE",
                "brandPicUrl":"http://brand-logo.oss-cn-shanghai.aliyuncs.com/INFINITE.png"
            }
        ]
    },
    {
        "Z":[
            {
                "brand":"之诺",
                "brandPicName":"ZHINUO",
                "brandPicUrl":"http://brand-logo.oss-cn-shanghai.aliyuncs.com/ZHINUO.png"
            },
            {
                "brand":"中欧",
                "brandPicName":"ZHONGOU",
                "brandPicUrl":"http://brand-logo.oss-cn-shanghai.aliyuncs.com/ZHONGOU.png"
            },
            {
                "brand":"众泰",
                "brandPicName":"ZOTYE",
                "brandPicUrl":"http://brand-logo.oss-cn-shanghai.aliyuncs.com/ZOTYE.png"
            },
            {
                "brand":"知豆",
                "brandPicName":"ZHIDOU",
                "brandPicUrl":"http://brand-logo.oss-cn-shanghai.aliyuncs.com/ZHIDOU.png"
            },
            {
                "brand":"中华",
                "brandPicName":"BRILLIANCE",
                "brandPicUrl":"http://brand-logo.oss-cn-shanghai.aliyuncs.com/BRILLIANCE.png"
            },
            {
                "brand":"中兴",
                "brandPicName":"ZHONGXING",
                "brandPicUrl":"http://brand-logo.oss-cn-shanghai.aliyuncs.com/ZHONGXING.png"
            },
            {
                "brand":"中顺",
                "brandPicName":"ZHONGSHUN",
                "brandPicUrl":"http://brand-logo.oss-cn-shanghai.aliyuncs.com/ZHONGSHUN.png"
            }
        ]
    }
];

let value = [
    {label:"奥迪",value:"AUDI"},
    {label:"别克",value:"BUICK"},
    {label:"比亚迪",value:"BYD"}
]

let options1=[
    {
        value: '江苏省',
        label: '江苏省',
        key:"key_1",
        checked:false,
        children: [
            {
                value: '徐州市',
                label: '徐州市',
                key:'key_10',
                checked:false,
                children: [
                    {
                        value: '丰县',
                        label: '丰县',
                        key:'key_101',
                        checked:false,
                    },
                    {
                        value: '邳州市',
                        label: '邳州市',
                        key:'key_102',
                        checked:false,
                    },
                    {
                        value: '新沂市',
                        label: '新沂市',
                        key:'key_103',
                        checked:false,
                    }
                ],
            },
            {
                value: '苏州市',
                label: '苏州市',
                key:'key_11',
                checked:false,
                children: [
                    {
                        value: '工业园区',
                        label: '工业园区',
                        key:'key_110',
                        checked:false,
                    },
                    {
                        value: '相城区',
                        label: '相城区',
                        key:'key_111',
                        checked:false,
                    },
                    {
                        value: '吴中区',
                        label: '吴中区',
                        key:'key_112',
                        checked:false,
                    }
                ],
            }
        ],
    },
    {
        value:'山东省',
        label:'山东省',
        key:'key_2',
        checked:false,
        children:[
            {
                value:'济南市',
                label:'济南市',
                key:'key_20',
                checked:false,
                children:[
                    {
                        value:'历下区',
                        label:'历下区',
                        key:'key_201',
                        checked:false,
                    }
                ]
            }
        ]
    }
]

export default class App extends Component{
    constructor(props){
        super(props);
        this.cJSelectChange = this.cjSelectChange.bind(this);
    }

    componentDidMount(){
      
    }

    cjSelectChange(info){
        console.log("value===",info)
        value = info;
    }
    
    render(){
        return(
            <div style={{ margin: 100 }}>
                <h1>Chejianer-lib Demo</h1>
                <hr /><br />
                <div style={{width:'100%'}}>
                    <CJSelect options={options} multiple={true} value={[]} defaultValue={[]} onChange={this.cjSelectChange} style={{marginTop:50,marginLeft:30,float:'left'}}/>
                    <CJCascade options={options1} multiple={false} style={{marginTop:50,marginLeft:30,float:'left'}}/>
                </div>
                
                <br/>
                <br/>
            </div>
        )
    }
}
ReactDOM.render(
    <App/>,document.getElementById('root')
)